# Change these first
owner: lordronz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Pog Bot
    url: $BOT_PING_URL
  - name: Ronz AMOGUS Bot
    url: $RONZAMOGUS_BOT_URL
    icon: https://ronz-amogus.vercel.app/favicon.ico
  - name: DTK Class Helper
    url: https://dtk-class.vercel.app
    icon: https://dtk-class.vercel.app/favicon.ico
  - name: Link Shortener
    url: https://lr-link.vercel.app
    icon: https://lr-link.vercel.app/favicon.ico
  - name: Pesan Awanama
    url: https://lr-anon.vercel.app
    icon: https://lr-anon.vercel.app/favicon.ico
  - name: Ronz Amogus Bot Documentation
    url: https://ronz-amogus.vercel.app
    icon: https://ronz-amogus.vercel.app/favicon.ico

assignees: # Users to assign downtime issues (optional)
  - LordRonz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/LordRonz/LordRonz.github.io/main/public/logo192.png
  name: LordRonz status website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Creator
      href: https://lr-link.vercel.app/
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
